import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Allow console.error / console.warn for error-boundary logging.
      // console.log is banned to prevent debug noise in committed code.
      "no-console": ["error", { allow: ["error", "warn"] }],
    },
  },
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      "next-env.d.ts",
      // Generated by Serwist at build time.
      "public/sw.js",
      "public/swe-worker*.js",
    ],
  },
];

export default eslintConfig;
